### ISSUE TITLE
 Consider upstreaming to linux-firmware

### ISSUE THREAD

**Issue by evelikov** [RPi-Distro/bluez-firmware#16] opened 2024-10-19 16:49 UTC
Greetings team,

Can you please consider sending these to the upstream linux-firmware repository? It should make the files easily accessible for people who want to run different distributions on their RPi devices more people. Plus it will reduce your maintenance burden in the mid to long run.

Thanks in advance o/

[1] https://gitlab.com/kernel-firmware/linux-firmware/

P.S. Sorry for the copy-paste :sweat_smile:

**Comment by popcornmix** [comment] 2024-10-21 13:16
Duplicate of #15

**Closed as completed by popcornmix** 2024-10-21 13:16 UTC

**Comment by evelikov** [comment] 2024-10-21 14:16
Was meant to file the second one against linux-nonfree. Sorry about that team o/
